version: 2
jobs:
  build:
    docker:
      # specify the version
      - image: circleci/golang:1.17-buster
        environment:
          GO111MODULE: "on"

    working_directory: /go/src/github.com/{{ORG_NAME}}/{{REPO_NAME}}
    steps:
      - checkout

      # specify any bash command here prefixed with `run: `
      - run: sudo apt-get update && sudo apt-get install ffmpeg
      - run: go mod download
      - run: go test -failfast -v -run=. ./...
      - run: go build
